<script setup lang="ts">
import { useLLMSettings, type MCPServerConfig } from '~/lib/llm/store'
import { discoverOpenRouterModels } from '~/lib/llm/providers'
const { settings, load, save, setSecret, getSecretPresent } = useLLMSettings(); onMounted(load)
const keyInputs = reactive<Record<string,string>>({ openrouter:'', openai:'', anthropic:'' }); const present = reactive<Record<string,boolean>>({ openrouter:false, openai:false, anthropic:false }); const freeModels = ref<any[]>([])
const newServer = reactive<MCPServerConfig>({ id:'', name:'', transport:'http', url:'', command:'', args:[], enabled:true })
onMounted(async () => { for (const p of ['openrouter','openai','anthropic']) present[p] = await getSecretPresent(p); try { freeModels.value = await discoverOpenRouterModels() } catch {} })
async function saveKey(provider:string) { const value = keyInputs[provider]?.trim(); if (!value) return; await setSecret(provider,value); keyInputs[provider]=''; present[provider]=true }
async function refreshFreeModels(){ freeModels.value=await discoverOpenRouterModels() }
function addMcp(){ if(!newServer.id||!newServer.name)return; settings.value.mcpServers.push({...newServer,args:newServer.args?[...newServer.args]:[]}); newServer.id='';newServer.name='';newServer.url='';newServer.command='';newServer.args=[];save() }
function removeMcp(i:number){settings.value.mcpServers.splice(i,1);save()}
</script>
<template>
  <div class="mx-auto max-w-5xl space-y-6"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-primary">System</p><h1 class="mt-2 text-3xl font-semibold">LLM & MCP Settings</h1><p class="mt-2 text-sm text-muted">Provider keys are stored through the Tauri desktop backend. They are not committed to the repository.</p></div>
    <UCard><h2 class="font-semibold">Providers</h2><div class="mt-4 grid gap-4 md:grid-cols-3"><div v-for="provider in ['openrouter','openai','anthropic']" :key="provider" class="space-y-2"><div class="flex items-center justify-between"><span class="font-medium capitalize">{{ provider }}</span><UBadge :color="present[provider]?'success':'neutral'" variant="subtle">{{present[provider]?'key saved':'not set'}}</UBadge></div><UInput v-model="keyInputs[provider]" type="password" placeholder="Paste API key"/><UButton size="sm" variant="soft" @click="saveKey(provider)">Save key</UButton></div></div>
      <div class="mt-6 grid gap-4 md:grid-cols-2"><USelect v-model="settings.preferredProvider" :items="[{label:'Auto — OpenRouter free first',value:'auto'},{label:'OpenRouter',value:'openrouter'},{label:'OpenAI',value:'openai'},{label:'Anthropic / Claude',value:'anthropic'}]" value-key="value" label-key="label"/><USwitch v-model="settings.autoFreeOnly" label="Prefer free models when auto-routing"/><USwitch v-model="settings.allowFrameworkWrite" label="Allow agent to modify framework files"/><USwitch v-model="settings.showToolActivity" label="Show tool activity"/></div><UButton class="mt-5" @click="save">Save settings</UButton>
    </UCard>
    <UCard><div class="flex items-center justify-between gap-3"><div><h2 class="font-semibold">OpenRouter free catalogue</h2><p class="text-sm text-muted">Discovered live from OpenRouter; availability can change.</p></div><UButton size="sm" variant="soft" @click="refreshFreeModels">Refresh</UButton></div><div class="mt-4 grid gap-2 sm:grid-cols-2"><div v-for="m in freeModels.slice(0,20)" :key="m.id" class="rounded-lg border border-zinc-800 p-3 text-sm"><div class="font-medium">{{m.name}}</div><div class="text-xs text-muted">{{m.id}} · {{m.context_length?.toLocaleString?.() ?? m.context_length}} context</div></div></div></UCard>
    <UCard><h2 class="font-semibold">MCP servers</h2><p class="mt-1 text-sm text-muted">Only servers with Enabled checked become visible to the agent. HTTP servers use URL; local servers use stdio command.</p><div class="mt-4 space-y-3"><div v-for="(server,index) in settings.mcpServers" :key="server.id" class="flex flex-col gap-3 rounded-lg border border-zinc-800 p-3 lg:flex-row lg:items-center"><div class="min-w-0 flex-1"><div class="font-medium">{{server.name}}</div><div class="text-xs text-muted">{{server.transport}} · {{server.url||server.command}}</div></div><USwitch v-model="server.enabled" label="Enabled"/><UButton size="xs" variant="ghost" color="error" @click="removeMcp(index)">Remove</UButton></div></div>
      <div class="mt-5 grid gap-3 md:grid-cols-2"><UInput v-model="newServer.id" placeholder="server-id"/><UInput v-model="newServer.name" placeholder="Display name"/><USelect v-model="newServer.transport" :items="[{label:'HTTP',value:'http'},{label:'stdio',value:'stdio'}]" value-key="value" label-key="label"/><UInput v-if="newServer.transport==='http'" v-model="newServer.url" placeholder="https://…/mcp"/><UInput v-else v-model="newServer.command" placeholder="Command, e.g. npx"/></div><UButton class="mt-4" @click="addMcp">Add MCP server</UButton>
    </UCard>
  </div>
</template>
