import type { ConnectorDefinition } from './types'

export const CONNECTOR_REGISTRY: ConnectorDefinition[] = [
  {
    id: 'discord',
    name: 'Discord',
    category: 'communication',
    description: 'Send and read Discord messages via MCP stdio bridge.',
    transport: 'mcp-stdio',
    mcpServerId: 'discord',
    auth: { type: 'env', envKeys: ['DISCORD_BOT_TOKEN'], vaultKeyPrefix: 'connector:discord' },
    capabilities: ['messaging', 'channels', 'agent-tool'],
    enabledByDefault: false,
    cursorParity: true,
    status: 'live',
    docsUrl: 'https://github.com/modelcontextprotocol/servers',
  },
  {
    id: 'gmail',
    name: 'Gmail',
    category: 'communication',
    description: 'Read and draft Gmail messages via Google OAuth PKCE.',
    transport: 'oauth',
    mcpServerId: 'gmail',
    auth: {
      type: 'oauth',
      envKeys: ['GOOGLE_CLIENT_ID', 'GOOGLE_ACCESS_TOKEN', 'GOOGLE_REFRESH_TOKEN'],
      oauthScopes: ['https://www.googleapis.com/auth/gmail.readonly'],
      vaultKeyPrefix: 'connector:gmail',
    },
    capabilities: ['email-read', 'email-draft', 'search'],
    enabledByDefault: false,
    cursorParity: true,
    status: 'live',
    docsUrl: 'https://developers.google.com/gmail/api',
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    category: 'storage',
    description: 'Index lab PDFs and research documents from Drive into local RAG.',
    transport: 'oauth',
    mcpServerId: 'google-drive',
    auth: {
      type: 'oauth',
      envKeys: ['GOOGLE_CLIENT_ID', 'GOOGLE_ACCESS_TOKEN', 'GOOGLE_REFRESH_TOKEN', 'GOOGLE_DRIVE_FOLDER_ID'],
      oauthScopes: ['https://www.googleapis.com/auth/drive.readonly'],
      vaultKeyPrefix: 'connector:google-drive',
    },
    capabilities: ['file-read', 'folder-sync', 'rag-ingest'],
    enabledByDefault: false,
    cursorParity: true,
    status: 'live',
    docsUrl: 'https://developers.google.com/drive',
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    category: 'communication',
    description: 'Read calendar events for experiment scheduling and protocol reminders.',
    transport: 'oauth',
    mcpServerId: 'google-calendar',
    auth: { type: 'oauth', oauthScopes: ['https://www.googleapis.com/auth/calendar.readonly'], vaultKeyPrefix: 'connector:google-calendar' },
    capabilities: ['calendar-read', 'reminders'],
    enabledByDefault: false,
    cursorParity: true,
    status: 'planned',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    category: 'ai',
    description: 'Hub models, datasets, Spaces, and inference API for genomic and bio models.',
    transport: 'hybrid',
    mcpServerId: 'huggingface',
    auth: { type: 'api-key', envKeys: ['HF_TOKEN', 'HUGGINGFACE_TOKEN'], vaultKeyPrefix: 'connector:huggingface' },
    capabilities: ['inference', 'model-search', 'dataset-browse', 'hub-fs'],
    enabledByDefault: true,
    cursorParity: true,
    status: 'live',
    docsUrl: 'https://huggingface.co/docs/hub',
  },
  {
    id: 'github',
    name: 'GitHub',
    category: 'devtools',
    description: 'Issues, PRs, and repository search via MCP stdio server.',
    transport: 'mcp-stdio',
    mcpServerId: 'github',
    auth: { type: 'env', envKeys: ['GITHUB_PERSONAL_ACCESS_TOKEN'], vaultKeyPrefix: 'connector:github' },
    capabilities: ['issues', 'pull-requests', 'code-search'],
    enabledByDefault: false,
    cursorParity: true,
    status: 'scaffold',
    docsUrl: 'https://github.com/modelcontextprotocol/servers',
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'communication',
    description: 'Slack workspace messaging via MCP stdio bridge.',
    transport: 'mcp-stdio',
    mcpServerId: 'slack',
    auth: { type: 'env', envKeys: ['SLACK_BOT_TOKEN', 'SLACK_TEAM_ID'], vaultKeyPrefix: 'connector:slack' },
    capabilities: ['messaging', 'channels'],
    enabledByDefault: false,
    cursorParity: true,
    status: 'scaffold',
  },
  {
    id: 'notion',
    name: 'Notion',
    category: 'storage',
    description: 'Read Notion pages and databases for protocol notes and experiment logs.',
    transport: 'mcp-stdio',
    mcpServerId: 'notion',
    auth: { type: 'api-key', envKeys: ['NOTION_API_KEY'], vaultKeyPrefix: 'connector:notion' },
    capabilities: ['pages', 'databases', 'search'],
    enabledByDefault: false,
    cursorParity: true,
    status: 'planned',
  },
  {
    id: 'tavily',
    name: 'Tavily',
    category: 'research',
    description: 'Web search optimized for research agents.',
    transport: 'mcp-stdio',
    mcpServerId: 'tavily',
    auth: { type: 'api-key', envKeys: ['TAVILY_API_KEY'], vaultKeyPrefix: 'connector:tavily' },
    capabilities: ['web-search', 'research'],
    enabledByDefault: false,
    cursorParity: true,
    status: 'scaffold',
  },
  {
    id: 'context7',
    name: 'Context7',
    category: 'research',
    description: 'Live library documentation lookup for frameworks and SDKs.',
    transport: 'mcp-stdio',
    mcpServerId: 'context7',
    auth: { type: 'api-key', envKeys: ['CONTEXT7_API_KEY'], vaultKeyPrefix: 'connector:context7' },
    capabilities: ['docs-search', 'library-lookup'],
    enabledByDefault: false,
    cursorParity: true,
    status: 'scaffold',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    category: 'devtools',
    description: 'Error monitoring and issue triage for deployed builds.',
    transport: 'api',
    auth: { type: 'api-key', envKeys: ['SENTRY_AUTH_TOKEN'], vaultKeyPrefix: 'connector:sentry' },
    capabilities: ['issues', 'releases', 'alerts'],
    enabledByDefault: false,
    cursorParity: true,
    status: 'planned',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'payments',
    description: 'Billing and subscription metadata (not used for clinical decisions).',
    transport: 'api',
    auth: { type: 'api-key', envKeys: ['STRIPE_SECRET_KEY'], vaultKeyPrefix: 'connector:stripe' },
    capabilities: ['billing-read'],
    enabledByDefault: false,
    cursorParity: true,
    status: 'planned',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'devtools',
    description: 'Postgres, auth, and storage for optional cloud sync.',
    transport: 'hybrid',
    auth: { type: 'api-key', envKeys: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'], vaultKeyPrefix: 'connector:supabase' },
    capabilities: ['database', 'auth', 'storage'],
    enabledByDefault: false,
    cursorParity: true,
    status: 'planned',
  },
  {
    id: 'convex',
    name: 'Convex',
    category: 'devtools',
    description: 'Realtime backend for collaborative experiment tracking.',
    transport: 'hybrid',
    auth: { type: 'api-key', envKeys: ['CONVEX_DEPLOY_KEY'], vaultKeyPrefix: 'connector:convex' },
    capabilities: ['database', 'functions'],
    enabledByDefault: false,
    cursorParity: true,
    status: 'planned',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'devtools',
    description: 'Deployment status and environment variables for web builds.',
    transport: 'api',
    auth: { type: 'api-key', envKeys: ['VERCEL_TOKEN'], vaultKeyPrefix: 'connector:vercel' },
    capabilities: ['deployments', 'env-vars'],
    enabledByDefault: false,
    cursorParity: true,
    status: 'planned',
  },
  {
    id: 'paper-search',
    name: 'Paper Search',
    category: 'research',
    description: 'Open-access literature search via paper-search-mcp (arXiv, PubMed, bioRxiv, Europe PMC, OpenAlex). Sci-Hub is disabled.',
    transport: 'mcp-stdio',
    mcpServerId: 'paper-search',
    auth: { type: 'env', envKeys: ['PAPER_SEARCH_MCP_UNPAYWALL_EMAIL'], vaultKeyPrefix: 'connector:paper-search' },
    capabilities: ['literature-search', 'doi-lookup', 'open-access-pdf'],
    enabledByDefault: false,
    cursorParity: false,
    status: 'scaffold',
    docsUrl: 'https://github.com/openags/paper-search-mcp',
  },
  {
    id: 'paper-qa',
    name: 'PaperQA',
    category: 'research',
    description: 'Citation-backed RAG over local scientific PDFs via PaperQA2. Optional local sidecar; does not replace intervention ranking.',
    transport: 'hybrid',
    mcpServerId: 'paper-qa',
    auth: { type: 'none', vaultKeyPrefix: 'connector:paper-qa' },
    capabilities: ['pdf-rag', 'citations', 'retraction-check'],
    enabledByDefault: false,
    cursorParity: false,
    status: 'scaffold',
    docsUrl: 'https://github.com/Future-House/paper-qa',
  },
  {
    id: 'local-deep-research',
    name: 'Local Deep Research',
    category: 'research',
    description: 'Optional local research sidecar (ldr-mcp) for cited summaries. Not merged into the Nuxt app.',
    transport: 'mcp-stdio',
    mcpServerId: 'local-deep-research',
    auth: { type: 'env', envKeys: ['LDR_LLM_PROVIDER'], vaultKeyPrefix: 'connector:local-deep-research' },
    capabilities: ['deep-research', 'citations', 'local-documents'],
    enabledByDefault: false,
    cursorParity: false,
    status: 'scaffold',
    docsUrl: 'https://github.com/LearningCircuit/local-deep-research',
  },
  {
    id: 'youtube-rag',
    name: 'YouTube → RAG',
    category: 'research',
    description: 'Fetch podcast and biohacking video transcripts into the local document RAG index.',
    transport: 'api',
    auth: { type: 'none', vaultKeyPrefix: 'connector:youtube-rag' },
    capabilities: ['transcript-ingest', 'rag-ingest', 'podcast-sync'],
    enabledByDefault: true,
    cursorParity: false,
    status: 'live',
    docsUrl: 'https://github.com/samson-art/transcriptor-mcp',
  },
  {
    id: 'transcriptor',
    name: 'Transcriptor MCP',
    category: 'research',
    description: 'Optional MCP sidecar for YouTube playlists, chapters, and videos without captions (Whisper).',
    transport: 'mcp-stdio',
    mcpServerId: 'transcriptor',
    auth: { type: 'none', vaultKeyPrefix: 'connector:transcriptor' },
    capabilities: ['transcript-ingest', 'playlist-sync', 'video-search'],
    enabledByDefault: false,
    cursorParity: false,
    status: 'scaffold',
    docsUrl: 'https://github.com/samson-art/transcriptor-mcp',
  },
  {
    id: 'pdf-inspector',
    name: 'PDF Inspector',
    category: 'research',
    description: 'Classifies lab PDFs as text vs scanned so the longevity import pipeline can choose OCR.',
    transport: 'api',
    auth: { type: 'none', vaultKeyPrefix: 'connector:pdf-inspector' },
    capabilities: ['pdf-classify', 'ocr-routing'],
    enabledByDefault: true,
    cursorParity: false,
    status: 'live',
    docsUrl: 'https://github.com/firecrawl/pdf-inspector',
  },
]

export function getConnector(id: string): ConnectorDefinition | undefined {
  return CONNECTOR_REGISTRY.find((entry) => entry.id === id)
}

export function listConnectorsByCategory(category: ConnectorDefinition['category']): ConnectorDefinition[] {
  return CONNECTOR_REGISTRY.filter((entry) => entry.category === category)
}
